name: Sort emoji & update progress
on:
  push:
    paths:
      - "incoming/**"
      - "sources/svg/**"
      - "scripts/**"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: python scripts/sort_emoji.py
      - run: python scripts/generate_progress.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Sort incoming emoji & update progress table"
